language: node_js
node_js:
- '8'
- '10'
- 'node'
deploy:
  provider: npm
  email: irfs@bbc.co.uk
  skip_cleanup: true
  api_key:
    secure: cSuf3iiNYM2jSjrk7xNxVLuZn+7S78jktze5MyFdK0rchgOessLY0yIDF9MZbhVbCXGgVbygp+dP5IMHPIDFCqC77WyaWCKdRfretb//RoiRAkEL9B6j8kJ//Sl7LPZ5yYpzotC2tF8zDrw0cucz1sXDTRN9x0C1do2O83hS/qk=
  on:
    tags: true
    repo: bbc/get-title
